export type Cell = null | 'full' | 'slab_bottom' | 'slab_top'

export interface Obstacle {
	name: string
	difficulty: number
	grid: Cell[][]
	groupId?: string
}

export interface ObstacleGroup {
	groupId: string
	difficulty: number
	obstacles: Obstacle[]
}

const F: Cell = 'full'
const _: Cell = null
const SB: Cell = 'slab_bottom'
const ST: Cell = 'slab_top'

export const singles: Obstacle[] = [
	{
		name: '1_1',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
		],
	},
	{
		name: '1_10',
		difficulty: 1,
		grid: [
			[F, F, _, _, _],
			[F, F, _, _, _],
			[F, F, _, _, _],
			[F, F, _, _, _],
			[F, F, _, _, _],
		],
	},
	{
		name: '1_11',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, F, F, F],
			[ST, ST, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '1_12',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[F, F, F, _, _],
			[F, F, F, ST, ST],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '1_13',
		difficulty: 1,
		grid: [
			[_, _, F, _, _],
			[_, _, F, _, _],
			[_, _, F, _, _],
			[_, _, F, _, _],
			[_, _, F, _, _],
		],
	},
	{
		name: '1_14',
		difficulty: 1,
		grid: [
			[_, F, F, _, _],
			[_, F, F, _, _],
			[_, F, F, _, _],
			[_, F, F, _, _],
			[_, F, F, _, _],
		],
	},
	{
		name: '1_15',
		difficulty: 1,
		grid: [
			[_, _, _, _, F],
			[_, _, _, _, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_16',
		difficulty: 1,
		grid: [
			[_, _, F, _, _],
			[_, _, F, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_17',
		difficulty: 1,
		grid: [
			[F, _, _, _, _],
			[F, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_18',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, _, F, _],
			[_, _, _, F, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_19',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, F, _, _, _],
			[_, F, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_2',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
		],
	},
	{
		name: '1_20',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, F],
			[_, _, _, _, F],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_21',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, F, _, _],
			[_, _, F, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_22',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[F, F, F, F, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_23',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[F, _, _, _, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_24',
		difficulty: 1,
		grid: [
			[F, _, _, _, F],
			[F, _, _, _, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_25',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[F, F, F, F, _],
			[F, F, F, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_26',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[F, _, _, F, F],
			[F, F, F, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_27',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, F, F, F, F],
			[F, F, F, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_28',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[F, F, _, _, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_29',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[_, _, F, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_3',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
		],
	},
	{
		name: '1_30',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[ST, ST, ST, ST, ST],
			[F, F, F, F, F],
			[SB, SB, SB, SB, SB],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_31',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[F, _, _, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_32',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[F, F, F, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_33',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, F, F, F],
			[F, F, F, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_34',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[F, F, _, _, F],
			[F, F, F, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_35',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[_, F, F, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_36',
		difficulty: 1,
		grid: [
			[F, _, _, F, F],
			[F, _, _, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_37',
		difficulty: 1,
		grid: [
			[F, F, _, _, F],
			[F, F, _, _, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_38',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, F, _, _, _],
			[_, F, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_39',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, F, _],
			[_, _, _, F, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_4',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
		],
	},
	{
		name: '1_40',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[F, _, _, _, _],
			[F, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_41',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, F, _, _],
			[_, _, F, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_42',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, _, _, F],
			[_, _, _, _, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_43',
		difficulty: 1,
		grid: [
			[_, F, _, _, _],
			[_, F, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_44',
		difficulty: 1,
		grid: [
			[_, _, _, F, _],
			[_, _, _, F, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_45',
		difficulty: 1,
		grid: [
			[_, _, F, F, _],
			[_, _, F, F, _],
			[_, _, F, F, _],
			[_, _, F, F, _],
			[_, _, F, F, _],
		],
	},
	{
		name: '1_46',
		difficulty: 1,
		grid: [
			[_, _, _, _, _],
			[_, _, _, _, _],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '1_5',
		difficulty: 1,
		grid: [
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
		],
	},
	{
		name: '1_6',
		difficulty: 1,
		grid: [
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
		],
	},
	{
		name: '1_7',
		difficulty: 1,
		grid: [
			[_, F, F, F, _],
			[_, F, F, F, _],
			[_, F, F, F, _],
			[_, F, F, F, _],
			[_, F, F, F, _],
		],
	},
	{
		name: '1_8',
		difficulty: 1,
		grid: [
			[F, F, F, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '1_9',
		difficulty: 1,
		grid: [
			[_, _, _, F, F],
			[_, _, _, F, F],
			[_, _, _, F, F],
			[_, _, _, F, F],
			[_, _, _, F, F],
		],
	},
	{
		name: '1_medium2_groupe3',
		difficulty: 1,
		grid: [
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
		],
	},
	{
		name: '2_1',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[_, _, F, _, _],
			[_, _, F, _, _],
			[_, _, F, _, _],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_10',
		difficulty: 2,
		grid: [
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_11',
		difficulty: 2,
		grid: [
			[_, F, F, F, F],
			[_, _, _, F, F],
			[_, _, _, F, F],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '2_12',
		difficulty: 2,
		grid: [
			[_, _, _, F, _],
			[_, F, _, F, _],
			[_, F, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '2_13',
		difficulty: 2,
		grid: [
			[F, _, _, _, F],
			[F, _, _, F, F],
			[F, _, F, F, _],
			[F, F, F, _, _],
			[F, F, _, _, _],
		],
	},
	{
		name: '2_14',
		difficulty: 2,
		grid: [
			[F, _, _, _, F],
			[F, _, _, _, F],
			[F, F, F, F, F],
			[F, SB, SB, SB, F],
			[F, _, _, _, F],
		],
	},
	{
		name: '2_15',
		difficulty: 2,
		grid: [
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_16',
		difficulty: 2,
		grid: [
			[F, SB, SB, SB, F],
			[F, _, _, _, F],
			[F, _, _, _, F],
			[F, ST, ST, ST, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_17',
		difficulty: 2,
		grid: [
			[SB, SB, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[ST, ST, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_18',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[F, F, _, _, F],
			[F, F, _, _, F],
			[F, F, _, _, F],
			[F, F, _, _, F],
		],
	},
	{
		name: '2_19',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[F, _, _, _, F],
			[F, _, _, _, F],
			[F, F, ST, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_2',
		difficulty: 2,
		grid: [
			[_, _, F, F, F],
			[_, _, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_20',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[SB, _, _, SB, SB],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '2_21',
		difficulty: 2,
		grid: [
			[F, F, ST, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, SB, _, _],
		],
	},
	{
		name: '2_22',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[_, _, F, F, _],
			[_, _, F, F, _],
			[_, _, F, F, _],
			[_, _, F, F, _],
		],
	},
	{
		name: '2_23',
		difficulty: 2,
		grid: [
			[_, _, F, F, F],
			[_, _, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_23w',
		difficulty: 2,
		grid: [
			[_, _, F, F, F],
			[_, _, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_24',
		difficulty: 2,
		grid: [
			[_, F, F, F, _],
			[_, F, F, F, _],
			[ST, F, F, F, ST],
			[F, F, F, F, F],
			[_, _, _, _, _],
		],
	},
	{
		name: '2_25',
		difficulty: 2,
		grid: [
			[_, F, _, _, _],
			[_, F, _, F, _],
			[_, _, _, F, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '2_26',
		difficulty: 2,
		grid: [
			[F, _, _, _, F],
			[F, F, _, _, F],
			[_, F, F, _, F],
			[_, _, F, F, F],
			[_, _, _, F, F],
		],
	},
	{
		name: '2_3',
		difficulty: 2,
		grid: [
			[_, _, F, _, _],
			[_, _, F, _, _],
			[ST, ST, F, ST, ST],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_4',
		difficulty: 2,
		grid: [
			[F, F, F, SB, SB],
			[F, F, F, _, _],
			[F, F, F, _, _],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_5',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[F, _, _, F, F],
			[F, _, _, F, F],
			[F, _, _, F, F],
			[F, _, _, F, F],
		],
	},
	{
		name: '2_6',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[F, _, _, _, F],
			[F, _, _, _, F],
			[F, _, _, _, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_7',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[SB, SB, _, _, SB],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '2_8',
		difficulty: 2,
		grid: [
			[_, _, ST, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, F, F, F],
			[_, _, SB, F, F],
		],
	},
	{
		name: '2_9',
		difficulty: 2,
		grid: [
			[F, F, F, F, F],
			[_, F, F, _, _],
			[_, F, F, _, _],
			[_, F, F, _, _],
			[_, F, F, _, _],
		],
	},
	{
		name: '3_1',
		difficulty: 3,
		grid: [
			[F, F, F, F, F],
			[_, _, _, _, _],
			[F, _, F, _, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '3_2',
		difficulty: 3,
		grid: [
			[F, F, _, F, F],
			[F, _, ST, _, F],
			[_, _, F, _, _],
			[F, _, SB, _, F],
			[F, F, _, F, F],
		],
	},
	{
		name: '3_3',
		difficulty: 3,
		grid: [
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '3_4',
		difficulty: 3,
		grid: [
			[_, F, _, F, _],
			[ST, F, _, F, ST],
			[F, F, F, F, F],
			[F, _, F, _, _],
			[F, _, _, _, _],
		],
	},
	{
		name: '3_5',
		difficulty: 3,
		grid: [
			[_, F, F, F, _],
			[_, F, _, F, _],
			[F, F, _, F, F],
			[F, F, ST, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '3_6',
		difficulty: 3,
		grid: [
			[F, F, F, F, F],
			[_, _, SB, _, _],
			[_, _, _, _, _],
			[ST, F, _, F, ST],
			[SB, F, F, F, SB],
		],
	},
	{
		name: '3_7',
		difficulty: 3,
		grid: [
			[_, _, _, _, _],
			[ST, ST, ST, ST, ST],
			[F, F, F, F, F],
			[F, ST, F, ST, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '3_8',
		difficulty: 3,
		grid: [
			[_, F, _, F, _],
			[_, F, ST, F, _],
			[F, F, F, F, F],
			[_, _, F, _, F],
			[_, _, _, _, F],
		],
	},
	{
		name: '4_1',
		difficulty: 4,
		grid: [
			[_, F, _, F, _],
			[ST, F, ST, F, ST],
			[F, _, F, _, F],
			[_, F, F, F, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '4_2',
		difficulty: 4,
		grid: [
			[F, _, F, _, F],
			[F, ST, F, ST, F],
			[F, F, F, F, F],
			[_, F, F, F, _],
			[_, _, _, _, _],
		],
	},
	{
		name: '5_1',
		difficulty: 5,
		grid: [
			[F, F, F, F, F],
			[F, _, _, _, F],
			[F, _, _, _, F],
			[F, ST, ST, ST, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '5_2',
		difficulty: 5,
		grid: [
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, _, _, _, F],
			[F, _, _, _, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '5_3',
		difficulty: 5,
		grid: [
			[F, SB, F, SB, F],
			[F, _, F, _, F],
			[F, F, F, F, F],
			[F, _, _, _, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '5_4',
		difficulty: 5,
		grid: [
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
			[_, _, _, _, _],
		],
	},
	{
		name: 'gate3x3',
		difficulty: 1,
		grid: [
			[_, _, F],
			[_, _, _],
			[_, _, F],
			[_, _, _],
			[_, _, F],
		],
	},
	{
		name: 'gate3x32',
		difficulty: 1,
		grid: [
			[_, F, _],
			[_, _, _],
			[_, F, _],
			[_, _, _],
			[_, F, _],
		],
	},
]

export const groups: ObstacleGroup[] = [
	{
		groupId: '1',
		difficulty: 1,
		obstacles: [
			{
				name: '1_1_1',
				difficulty: 1,
				groupId: '1',
				grid: [
					[F, F, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
				],
			},
			{
				name: '2_1_1',
				difficulty: 1,
				groupId: '1',
				grid: [
					[_, _, _, _, _],
					[_, _, _, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_1_1',
				difficulty: 1,
				groupId: '1',
				grid: [
					[_, _, _, _, _],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '4_1_1',
				difficulty: 1,
				groupId: '1',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
		],
	},
	{
		groupId: '10',
		difficulty: 2,
		obstacles: [
			{
				name: '1_2_10',
				difficulty: 2,
				groupId: '10',
				grid: [
					[_, _, _, _, _],
					[F, F, F, _, _],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '2_2_10',
				difficulty: 2,
				groupId: '10',
				grid: [
					[_, _, _, _, _],
					[F, F, _, _, F],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '3_2_10',
				difficulty: 2,
				groupId: '10',
				grid: [
					[_, _, _, _, _],
					[F, _, _, F, F],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_2_10',
				difficulty: 2,
				groupId: '10',
				grid: [
					[_, _, _, _, _],
					[_, _, F, F, F],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '5_2_10',
				difficulty: 2,
				groupId: '10',
				grid: [
					[_, _, _, _, _],
					[F, F, F, _, _],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '6_2_10',
				difficulty: 2,
				groupId: '10',
				grid: [
					[_, _, _, _, _],
					[F, _, _, F, F],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
		],
	},
	{
		groupId: '12',
		difficulty: 4,
		obstacles: [
			{
				name: '1_4_12',
				difficulty: 4,
				groupId: '12',
				grid: [
					[F, F, _, F, F],
					[F, _, _, _, F],
					[_, _, F, _, _],
					[F, _, _, _, F],
					[F, F, _, F, F],
				],
			},
			{
				name: '2_4_12',
				difficulty: 4,
				groupId: '12',
				grid: [
					[_, F, _, F, _],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[_, F, F, F, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '3_4_12',
				difficulty: 4,
				groupId: '12',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_4_12',
				difficulty: 4,
				groupId: '12',
				grid: [
					[_, _, _, _, _],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
		],
	},
	{
		groupId: '15',
		difficulty: 2,
		obstacles: [
			{
				name: '1_2_15',
				difficulty: 2,
				groupId: '15',
				grid: [
					[F, F, F, F, F],
					[_, _, F, _, _],
					[_, _, F, _, _],
					[_, _, F, _, _],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_2_15',
				difficulty: 2,
				groupId: '15',
				grid: [
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
				],
			},
			{
				name: '3_2_15',
				difficulty: 2,
				groupId: '15',
				grid: [
					[F, F, F, F, F],
					[_, _, F, _, _],
					[_, _, F, _, _],
					[_, _, F, _, _],
					[F, F, F, F, F],
				],
			},
			{
				name: '4_2_15',
				difficulty: 2,
				groupId: '15',
				grid: [
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
				],
			},
			{
				name: '5_2_15',
				difficulty: 2,
				groupId: '15',
				grid: [
					[_, _, F, _, _],
					[_, _, F, _, _],
					[ST, ST, F, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '6_2_15',
				difficulty: 2,
				groupId: '15',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '7_2_15',
				difficulty: 2,
				groupId: '15',
				grid: [
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
				],
			},
		],
	},
	{
		groupId: '16',
		difficulty: 4,
		obstacles: [
			{
				name: '1_4_16',
				difficulty: 4,
				groupId: '16',
				grid: [
					[F, _, F, _, F],
					[F, ST, F, ST, F],
					[F, F, F, F, F],
					[F, ST, F, ST, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_4_16',
				difficulty: 4,
				groupId: '16',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '3_4_16',
				difficulty: 4,
				groupId: '16',
				grid: [
					[_, F, _, F, _],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[F, _, F, _, F],
					[_, F, F, F, _],
				],
			},
			{
				name: '4_4_16',
				difficulty: 4,
				groupId: '16',
				grid: [
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '5_4_16',
				difficulty: 4,
				groupId: '16',
				grid: [
					[_, _, _, _, _],
					[_, _, _, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '6_4_16',
				difficulty: 4,
				groupId: '16',
				grid: [
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '7_4_16',
				difficulty: 4,
				groupId: '16',
				grid: [
					[F, F, F, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
				],
			},
		],
	},
	{
		groupId: '17',
		difficulty: 4,
		obstacles: [
			{
				name: '1_4_17',
				difficulty: 4,
				groupId: '17',
				grid: [
					[_, F, _, F, _],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[F, _, F, _, F],
					[_, F, F, F, _],
				],
			},
			{
				name: '2_4_17',
				difficulty: 4,
				groupId: '17',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '3_4_17',
				difficulty: 4,
				groupId: '17',
				grid: [
					[F, _, F, _, F],
					[F, ST, F, ST, F],
					[F, F, F, F, F],
					[_, F, F, F, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_4_17',
				difficulty: 4,
				groupId: '17',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '5_4_17',
				difficulty: 4,
				groupId: '17',
				grid: [
					[_, F, _, F, _],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[F, _, F, _, F],
					[_, F, F, F, _],
				],
			},
		],
	},
	{
		groupId: '18',
		difficulty: 3,
		obstacles: [
			{
				name: '1_3_18',
				difficulty: 3,
				groupId: '18',
				grid: [
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_3_18',
				difficulty: 3,
				groupId: '18',
				grid: [
					[_, _, F, F, F],
					[_, _, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_3_18',
				difficulty: 3,
				groupId: '18',
				grid: [
					[F, F, F, _, _],
					[F, F, F, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '19',
		difficulty: 1,
		obstacles: [
			{
				name: '1_1_19',
				difficulty: 1,
				groupId: '19',
				grid: [
					[_, F, _, _, _],
					[_, F, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '2_1_19',
				difficulty: 1,
				groupId: '19',
				grid: [
					[_, _, _, _, _],
					[_, _, _, F, _],
					[_, _, _, F, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '3_1_19',
				difficulty: 1,
				groupId: '19',
				grid: [
					[F, _, _, _, _],
					[F, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_1_19',
				difficulty: 1,
				groupId: '19',
				grid: [
					[_, _, F, _, _],
					[_, _, F, _, _],
					[F, F, F, F, F],
					[_, _, F, _, _],
					[_, _, F, _, _],
				],
			},
			{
				name: '5_1_19',
				difficulty: 1,
				groupId: '19',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
		],
	},
	{
		groupId: '2',
		difficulty: 5,
		obstacles: [
			{
				name: '10_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[_, _, F, F, F],
					[ST, ST, F, _, _],
					[F, F, F, _, _],
					[F, F, F, ST, ST],
					[F, F, F, F, F],
				],
			},
			{
				name: '1_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
				],
			},
			{
				name: '2_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '3_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[F, F, _, _, F],
					[F, F, _, _, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '5_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[F, F, F, _, _],
					[F, F, F, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '6_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '7_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[F, F, F, _, _],
					[F, F, F, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '8_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[_, _, F, F, F],
					[_, _, F, F, F],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '9_5_2',
				difficulty: 5,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
		],
	},
	{
		groupId: '21',
		difficulty: 2,
		obstacles: [
			{
				name: '1_2_21',
				difficulty: 2,
				groupId: '21',
				grid: [
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_2_21',
				difficulty: 2,
				groupId: '21',
				grid: [
					[_, _, F, _, _],
					[_, _, F, _, _],
					[_, _, F, _, _],
					[_, _, F, _, _],
					[_, _, F, _, _],
				],
			},
			{
				name: '3_2_21',
				difficulty: 2,
				groupId: '21',
				grid: [
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
				],
			},
			{
				name: '4_2_21',
				difficulty: 2,
				groupId: '21',
				grid: [
					[_, F, F, F, _],
					[ST, F, SB, F, ST],
					[F, F, _, F, F],
					[F, F, _, F, F],
					[_, F, F, F, _],
				],
			},
			{
				name: '5_2_21',
				difficulty: 2,
				groupId: '21',
				grid: [
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '6_2_21',
				difficulty: 2,
				groupId: '21',
				grid: [
					[_, _, _, _, _],
					[_, _, _, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '22',
		difficulty: 5,
		obstacles: [
			{
				name: '1_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, _, _],
				],
			},
			{
				name: '2_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, _, _],
				],
			},
			{
				name: '3_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[_, _, F, F, F],
					[_, _, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '4_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
				],
			},
			{
				name: '5_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
				],
			},
			{
				name: '6_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '7_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[_, _, F, F, F],
					[_, _, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '8_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[_, F, _, _, _],
					[_, F, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '9_5_22',
				difficulty: 5,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
		],
	},
	{
		groupId: '23',
		difficulty: 3,
		obstacles: [
			{
				name: '1_3_23',
				difficulty: 3,
				groupId: '23',
				grid: [
					[F, F, F, F, F],
					[_, _, F, _, _],
					[_, _, F, _, _],
					[_, _, F, _, _],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_3_23',
				difficulty: 3,
				groupId: '23',
				grid: [
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
				],
			},
			{
				name: '3_3_23',
				difficulty: 3,
				groupId: '23',
				grid: [
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '4_3_23',
				difficulty: 3,
				groupId: '23',
				grid: [
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '5_3_23',
				difficulty: 3,
				groupId: '23',
				grid: [
					[F, F, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
				],
			},
			{
				name: '6_3_23',
				difficulty: 3,
				groupId: '23',
				grid: [
					[_, _, _, _, _],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '24',
		difficulty: 1,
		obstacles: [
			{
				name: '1_1_24',
				difficulty: 1,
				groupId: '24',
				grid: [
					[_, _, F, _, _],
					[_, _, F, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[_, _, _, _, _],
				],
			},
			{
				name: '2_1_24',
				difficulty: 1,
				groupId: '24',
				grid: [
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_1_24',
				difficulty: 1,
				groupId: '24',
				grid: [
					[F, F, _, _, F],
					[F, F, _, _, F],
					[F, F, _, _, F],
					[F, F, _, _, F],
					[F, F, _, _, F],
				],
			},
			{
				name: '4_1_24',
				difficulty: 1,
				groupId: '24',
				grid: [
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
				],
			},
			{
				name: '5_1_24',
				difficulty: 1,
				groupId: '24',
				grid: [
					[_, _, _, _, _],
					[_, F, _, _, _],
					[_, F, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
		],
	},
	{
		groupId: '25',
		difficulty: 3,
		obstacles: [
			{
				name: '1_3_25',
				difficulty: 3,
				groupId: '25',
				grid: [
					[_, _, _, _, _],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '2_3_25',
				difficulty: 3,
				groupId: '25',
				grid: [
					[_, _, _, _, _],
					[F, ST, F, ST, F],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '3_3_25',
				difficulty: 3,
				groupId: '25',
				grid: [
					[_, _, _, _, _],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_3_25',
				difficulty: 3,
				groupId: '25',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '3',
		difficulty: 1,
		obstacles: [
			{
				name: '1_1_3',
				difficulty: 1,
				groupId: '3',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '2_1_3',
				difficulty: 1,
				groupId: '3',
				grid: [
					[_, _, F, _, _],
					[_, _, F, _, _],
					[F, F, F, F, F],
					[_, _, F, _, _],
					[_, _, F, _, _],
				],
			},
			{
				name: '3_1_3',
				difficulty: 1,
				groupId: '3',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_1_3',
				difficulty: 1,
				groupId: '3',
				grid: [
					[_, _, F, _, _],
					[_, _, F, _, _],
					[F, F, F, F, F],
					[_, _, F, _, _],
					[_, _, F, _, _],
				],
			},
			{
				name: '5_1_3',
				difficulty: 1,
				groupId: '3',
				grid: [
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '6',
		difficulty: 4,
		obstacles: [
			{
				name: '1_4_6',
				difficulty: 4,
				groupId: '6',
				grid: [
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
				],
			},
			{
				name: '2_4_6',
				difficulty: 4,
				groupId: '6',
				grid: [
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
					[_, F, F, F, _],
				],
			},
			{
				name: '3_4_6',
				difficulty: 4,
				groupId: '6',
				grid: [
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
				],
			},
			{
				name: '4_4_6',
				difficulty: 4,
				groupId: '6',
				grid: [
					[F, _, _, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
				],
			},
			{
				name: '5_4_6',
				difficulty: 4,
				groupId: '6',
				grid: [
					[F, F, _, _, F],
					[F, F, _, _, F],
					[F, F, _, _, F],
					[F, F, _, _, F],
					[F, F, _, _, F],
				],
			},
			{
				name: '6_4_6',
				difficulty: 4,
				groupId: '6',
				grid: [
					[F, _, _, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
					[F, _, _, F, F],
				],
			},
			{
				name: '7_4_6',
				difficulty: 4,
				groupId: '6',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '8_4_6',
				difficulty: 4,
				groupId: '6',
				grid: [
					[_, _, _, _, _],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '7',
		difficulty: 1,
		obstacles: [
			{
				name: '1_1_7',
				difficulty: 1,
				groupId: '7',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '2_1_7',
				difficulty: 1,
				groupId: '7',
				grid: [
					[_, _, _, _, _],
					[_, _, _, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_1_7',
				difficulty: 1,
				groupId: '7',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_1_7',
				difficulty: 1,
				groupId: '7',
				grid: [
					[_, _, _, _, _],
					[_, _, _, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '5_1_7',
				difficulty: 1,
				groupId: '7',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '8_1_7',
				difficulty: 1,
				groupId: '7',
				grid: [
					[_, _, _, _, _],
					[_, _, _, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '9_1_7',
				difficulty: 1,
				groupId: '7',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
		],
	},
	{
		groupId: '8',
		difficulty: 2,
		obstacles: [
			{
				name: '1_2_8',
				difficulty: 2,
				groupId: '8',
				grid: [
					[F, F, F, F, F],
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, ST, ST],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_2_8',
				difficulty: 2,
				groupId: '8',
				grid: [
					[F, F, F, _, _],
					[F, F, F, _, _],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_2_8',
				difficulty: 2,
				groupId: '8',
				grid: [
					[F, F, F, F, F],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
					[_, _, _, _, _],
				],
			},
			{
				name: '4_2_8',
				difficulty: 2,
				groupId: '8',
				grid: [
					[_, _, F, F, F],
					[_, _, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '5_2_8',
				difficulty: 2,
				groupId: '8',
				grid: [
					[F, F, F, F, F],
					[_, _, F, F, F],
					[_, _, F, F, F],
					[ST, ST, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '6_2_8',
				difficulty: 2,
				groupId: '8',
				grid: [
					[F, _, _, _, F],
					[F, _, _, _, F],
					[F, F, F, F, F],
					[F, _, _, _, F],
					[F, _, _, _, F],
				],
			},
		],
	},
]
