export const PATTERN_WIDTH = 5
export const PATTERN_HEIGHT = 5

export const WALL_SPAWN_AHEAD = 30
export const WALL_PASS_BEHIND = 10
export const WALL_TRAVEL_DISTANCE = WALL_SPAWN_AHEAD + WALL_PASS_BEHIND

export const WALL_SPEED = 0.5
export const WALL_TRAVEL_TICKS = Math.round(WALL_TRAVEL_DISTANCE / WALL_SPEED)
export const WALL_REACH_TICKS = Math.round(WALL_SPAWN_AHEAD / WALL_SPEED)
export const WALL_TRAVEL_OFFSET = WALL_REACH_TICKS + 4
export const WALL_LIFETIME = WALL_TRAVEL_TICKS + 20

export const MOVE_SCALE = 1000
export const MOVE_NUMERATOR = WALL_TRAVEL_DISTANCE * MOVE_SCALE
