import { CellType, Difficulty } from '.'
import type { Cell } from '.'
export { CellType, type Cell } from '.'

export interface Obstacle {
	name: string
	difficulty: Difficulty
	grid: Cell[][]
	groupId?: string
}

export interface ObstacleGroup {
	groupId: string
	difficulty: Difficulty
	obstacles: Obstacle[]
}

const F = CellType.FULL
const E: Cell = null
const SB = CellType.SLAB_BOTTOM
const ST = CellType.SLAB_TOP

export const singles: Obstacle[] = [
	{
		name: '1_1',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
		],
	},
	{
		name: '1_10',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, E, E, E],
			[F, F, E, E, E],
			[F, F, E, E, E],
			[F, F, E, E, E],
			[F, F, E, E, E],
		],
	},
	{
		name: '1_11',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, F, F, F],
			[ST, ST, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '1_12',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[F, F, F, E, E],
			[F, F, F, ST, ST],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '1_13',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, F, E, E],
			[E, E, F, E, E],
			[E, E, F, E, E],
			[E, E, F, E, E],
			[E, E, F, E, E],
		],
	},
	{
		name: '1_14',
		difficulty: Difficulty.EASY,
		grid: [
			[E, F, F, E, E],
			[E, F, F, E, E],
			[E, F, F, E, E],
			[E, F, F, E, E],
			[E, F, F, E, E],
		],
	},
	{
		name: '1_15',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, F],
			[E, E, E, E, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_16',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, F, E, E],
			[E, E, F, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_17',
		difficulty: Difficulty.EASY,
		grid: [
			[F, E, E, E, E],
			[F, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_18',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, E, F, E],
			[E, E, E, F, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_19',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, F, E, E, E],
			[E, F, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_2',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
		],
	},
	{
		name: '1_20',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, F],
			[E, E, E, E, F],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_21',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, F, E, E],
			[E, E, F, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_22',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[F, F, F, F, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_23',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[F, E, E, E, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_24',
		difficulty: Difficulty.EASY,
		grid: [
			[F, E, E, E, F],
			[F, E, E, E, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_25',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[F, F, F, F, E],
			[F, F, F, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_26',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[F, E, E, F, F],
			[F, F, F, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_27',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, F, F, F, F],
			[F, F, F, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_28',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[F, F, E, E, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_29',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[E, E, F, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_3',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
		],
	},
	{
		name: '1_30',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[ST, ST, ST, ST, ST],
			[F, F, F, F, F],
			[SB, SB, SB, SB, SB],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_31',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[F, E, E, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_32',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[F, F, F, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_33',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, F, F, F],
			[F, F, F, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_34',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[F, F, E, E, F],
			[F, F, F, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_35',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[E, F, F, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_36',
		difficulty: Difficulty.EASY,
		grid: [
			[F, E, E, F, F],
			[F, E, E, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_37',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, E, E, F],
			[F, F, E, E, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_38',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, F, E, E, E],
			[E, F, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_39',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, F, E],
			[E, E, E, F, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_4',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
		],
	},
	{
		name: '1_40',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[F, E, E, E, E],
			[F, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_41',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, F, E, E],
			[E, E, F, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_42',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, E, E, F],
			[E, E, E, E, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_43',
		difficulty: Difficulty.EASY,
		grid: [
			[E, F, E, E, E],
			[E, F, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_44',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, F, E],
			[E, E, E, F, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_45',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, F, F, E],
			[E, E, F, F, E],
			[E, E, F, F, E],
			[E, E, F, F, E],
			[E, E, F, F, E],
		],
	},
	{
		name: '1_46',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, E, E],
			[E, E, E, E, E],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '1_5',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
		],
	},
	{
		name: '1_6',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
		],
	},
	{
		name: '1_7',
		difficulty: Difficulty.EASY,
		grid: [
			[E, F, F, F, E],
			[E, F, F, F, E],
			[E, F, F, F, E],
			[E, F, F, F, E],
			[E, F, F, F, E],
		],
	},
	{
		name: '1_8',
		difficulty: Difficulty.EASY,
		grid: [
			[F, F, F, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '1_9',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, E, F, F],
			[E, E, E, F, F],
			[E, E, E, F, F],
			[E, E, E, F, F],
			[E, E, E, F, F],
		],
	},
	{
		name: '1_medium2_group3',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
		],
	},
	{
		name: '2_1',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[E, E, F, E, E],
			[E, E, F, E, E],
			[E, E, F, E, E],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_10',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_11',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, F, F, F, F],
			[E, E, E, F, F],
			[E, E, E, F, F],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '2_12',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, E, E, F, E],
			[E, F, E, F, E],
			[E, F, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '2_13',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, E, E, E, F],
			[F, E, E, F, F],
			[F, E, F, F, E],
			[F, F, F, E, E],
			[F, F, E, E, E],
		],
	},
	{
		name: '2_14',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, E, E, E, F],
			[F, E, E, E, F],
			[F, F, F, F, F],
			[F, SB, SB, SB, F],
			[F, E, E, E, F],
		],
	},
	{
		name: '2_15',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_16',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, SB, SB, SB, F],
			[F, E, E, E, F],
			[F, E, E, E, F],
			[F, ST, ST, ST, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_17',
		difficulty: Difficulty.NORMAL,
		grid: [
			[SB, SB, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[ST, ST, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_18',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[F, F, E, E, F],
			[F, F, E, E, F],
			[F, F, E, E, F],
			[F, F, E, E, F],
		],
	},
	{
		name: '2_19',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[F, E, E, E, F],
			[F, E, E, E, F],
			[F, F, ST, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_2',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, E, F, F, F],
			[E, E, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_20',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[SB, E, E, SB, SB],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '2_21',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, ST, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, SB, E, E],
		],
	},
	{
		name: '2_22',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[E, E, F, F, E],
			[E, E, F, F, E],
			[E, E, F, F, E],
			[E, E, F, F, E],
		],
	},
	{
		name: '2_23',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, E, F, F, F],
			[E, E, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_23w',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, E, F, F, F],
			[E, E, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_24',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, F, F, F, E],
			[E, F, F, F, E],
			[ST, F, F, F, ST],
			[F, F, F, F, F],
			[E, E, E, E, E],
		],
	},
	{
		name: '2_25',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, F, E, E, E],
			[E, F, E, F, E],
			[E, E, E, F, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '2_26',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, E, E, E, F],
			[F, F, E, E, F],
			[E, F, F, E, F],
			[E, E, F, F, F],
			[E, E, E, F, F],
		],
	},
	{
		name: '2_3',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, E, F, E, E],
			[E, E, F, E, E],
			[ST, ST, F, ST, ST],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_4',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, SB, SB],
			[F, F, F, E, E],
			[F, F, F, E, E],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_5',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[F, E, E, F, F],
			[F, E, E, F, F],
			[F, E, E, F, F],
			[F, E, E, F, F],
		],
	},
	{
		name: '2_6',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[F, E, E, E, F],
			[F, E, E, E, F],
			[F, E, E, E, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '2_7',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[SB, SB, E, E, SB],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '2_8',
		difficulty: Difficulty.NORMAL,
		grid: [
			[E, E, ST, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, F, F, F],
			[E, E, SB, F, F],
		],
	},
	{
		name: '2_9',
		difficulty: Difficulty.NORMAL,
		grid: [
			[F, F, F, F, F],
			[E, F, F, E, E],
			[E, F, F, E, E],
			[E, F, F, E, E],
			[E, F, F, E, E],
		],
	},
	{
		name: '3_1',
		difficulty: Difficulty.HARD,
		grid: [
			[F, F, F, F, F],
			[E, E, E, E, E],
			[F, E, F, E, F],
			[F, F, F, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '3_2',
		difficulty: Difficulty.HARD,
		grid: [
			[F, F, E, F, F],
			[F, E, ST, E, F],
			[E, E, F, E, E],
			[F, E, SB, E, F],
			[F, F, E, F, F],
		],
	},
	{
		name: '3_3',
		difficulty: Difficulty.HARD,
		grid: [
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '3_4',
		difficulty: Difficulty.HARD,
		grid: [
			[E, F, E, F, E],
			[ST, F, E, F, ST],
			[F, F, F, F, F],
			[F, E, F, E, E],
			[F, E, E, E, E],
		],
	},
	{
		name: '3_5',
		difficulty: Difficulty.HARD,
		grid: [
			[E, F, F, F, E],
			[E, F, E, F, E],
			[F, F, E, F, F],
			[F, F, ST, F, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '3_6',
		difficulty: Difficulty.HARD,
		grid: [
			[F, F, F, F, F],
			[E, E, SB, E, E],
			[E, E, E, E, E],
			[ST, F, E, F, ST],
			[SB, F, F, F, SB],
		],
	},
	{
		name: '3_7',
		difficulty: Difficulty.HARD,
		grid: [
			[E, E, E, E, E],
			[ST, ST, ST, ST, ST],
			[F, F, F, F, F],
			[F, ST, F, ST, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '3_8',
		difficulty: Difficulty.HARD,
		grid: [
			[E, F, E, F, E],
			[E, F, ST, F, E],
			[F, F, F, F, F],
			[E, E, F, E, F],
			[E, E, E, E, F],
		],
	},
	{
		name: '4_1',
		difficulty: Difficulty.EXPERT,
		grid: [
			[E, F, E, F, E],
			[ST, F, ST, F, ST],
			[F, E, F, E, F],
			[E, F, F, F, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '4_2',
		difficulty: Difficulty.EXPERT,
		grid: [
			[F, E, F, E, F],
			[F, ST, F, ST, F],
			[F, F, F, F, F],
			[E, F, F, F, E],
			[E, E, E, E, E],
		],
	},
	{
		name: '5_1',
		difficulty: Difficulty.MASTER,
		grid: [
			[F, F, F, F, F],
			[F, E, E, E, F],
			[F, E, E, E, F],
			[F, ST, ST, ST, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '5_2',
		difficulty: Difficulty.MASTER,
		grid: [
			[F, F, F, F, F],
			[F, F, F, F, F],
			[F, E, E, E, F],
			[F, E, E, E, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '5_3',
		difficulty: Difficulty.MASTER,
		grid: [
			[F, SB, F, SB, F],
			[F, E, F, E, F],
			[F, F, F, F, F],
			[F, E, E, E, F],
			[F, F, F, F, F],
		],
	},
	{
		name: '5_4',
		difficulty: Difficulty.MASTER,
		grid: [
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
			[E, E, E, E, E],
		],
	},
	{
		name: 'gate3x3',
		difficulty: Difficulty.EASY,
		grid: [
			[E, E, F],
			[E, E, E],
			[E, E, F],
			[E, E, E],
			[E, E, F],
		],
	},
	{
		name: 'gate3x32',
		difficulty: Difficulty.EASY,
		grid: [
			[E, F, E],
			[E, E, E],
			[E, F, E],
			[E, E, E],
			[E, F, E],
		],
	},
]

export const groups: ObstacleGroup[] = [
	{
		groupId: '1',
		difficulty: Difficulty.EASY,
		obstacles: [
			{
				name: '1_1_1',
				difficulty: Difficulty.EASY,
				groupId: '1',
				grid: [
					[F, F, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
				],
			},
			{
				name: '2_1_1',
				difficulty: Difficulty.EASY,
				groupId: '1',
				grid: [
					[E, E, E, E, E],
					[E, E, E, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_1_1',
				difficulty: Difficulty.EASY,
				groupId: '1',
				grid: [
					[E, E, E, E, E],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '4_1_1',
				difficulty: Difficulty.EASY,
				groupId: '1',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
		],
	},
	{
		groupId: '10',
		difficulty: Difficulty.NORMAL,
		obstacles: [
			{
				name: '1_2_10',
				difficulty: Difficulty.NORMAL,
				groupId: '10',
				grid: [
					[E, E, E, E, E],
					[F, F, F, E, E],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '2_2_10',
				difficulty: Difficulty.NORMAL,
				groupId: '10',
				grid: [
					[E, E, E, E, E],
					[F, F, E, E, F],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '3_2_10',
				difficulty: Difficulty.NORMAL,
				groupId: '10',
				grid: [
					[E, E, E, E, E],
					[F, E, E, F, F],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_2_10',
				difficulty: Difficulty.NORMAL,
				groupId: '10',
				grid: [
					[E, E, E, E, E],
					[E, E, F, F, F],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '5_2_10',
				difficulty: Difficulty.NORMAL,
				groupId: '10',
				grid: [
					[E, E, E, E, E],
					[F, F, F, E, E],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '6_2_10',
				difficulty: Difficulty.NORMAL,
				groupId: '10',
				grid: [
					[E, E, E, E, E],
					[F, E, E, F, F],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
		],
	},
	{
		groupId: '12',
		difficulty: Difficulty.EXPERT,
		obstacles: [
			{
				name: '1_4_12',
				difficulty: Difficulty.EXPERT,
				groupId: '12',
				grid: [
					[F, F, E, F, F],
					[F, E, E, E, F],
					[E, E, F, E, E],
					[F, E, E, E, F],
					[F, F, E, F, F],
				],
			},
			{
				name: '2_4_12',
				difficulty: Difficulty.EXPERT,
				groupId: '12',
				grid: [
					[E, F, E, F, E],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[E, F, F, F, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '3_4_12',
				difficulty: Difficulty.EXPERT,
				groupId: '12',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_4_12',
				difficulty: Difficulty.EXPERT,
				groupId: '12',
				grid: [
					[E, E, E, E, E],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
		],
	},
	{
		groupId: '15',
		difficulty: Difficulty.NORMAL,
		obstacles: [
			{
				name: '1_2_15',
				difficulty: Difficulty.NORMAL,
				groupId: '15',
				grid: [
					[F, F, F, F, F],
					[E, E, F, E, E],
					[E, E, F, E, E],
					[E, E, F, E, E],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_2_15',
				difficulty: Difficulty.NORMAL,
				groupId: '15',
				grid: [
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
				],
			},
			{
				name: '3_2_15',
				difficulty: Difficulty.NORMAL,
				groupId: '15',
				grid: [
					[F, F, F, F, F],
					[E, E, F, E, E],
					[E, E, F, E, E],
					[E, E, F, E, E],
					[F, F, F, F, F],
				],
			},
			{
				name: '4_2_15',
				difficulty: Difficulty.NORMAL,
				groupId: '15',
				grid: [
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
				],
			},
			{
				name: '5_2_15',
				difficulty: Difficulty.NORMAL,
				groupId: '15',
				grid: [
					[E, E, F, E, E],
					[E, E, F, E, E],
					[ST, ST, F, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '6_2_15',
				difficulty: Difficulty.NORMAL,
				groupId: '15',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '7_2_15',
				difficulty: Difficulty.NORMAL,
				groupId: '15',
				grid: [
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
				],
			},
		],
	},
	{
		groupId: '16',
		difficulty: Difficulty.EXPERT,
		obstacles: [
			{
				name: '1_4_16',
				difficulty: Difficulty.EXPERT,
				groupId: '16',
				grid: [
					[F, E, F, E, F],
					[F, ST, F, ST, F],
					[F, F, F, F, F],
					[F, ST, F, ST, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_4_16',
				difficulty: Difficulty.EXPERT,
				groupId: '16',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '3_4_16',
				difficulty: Difficulty.EXPERT,
				groupId: '16',
				grid: [
					[E, F, E, F, E],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[F, E, F, E, F],
					[E, F, F, F, E],
				],
			},
			{
				name: '4_4_16',
				difficulty: Difficulty.EXPERT,
				groupId: '16',
				grid: [
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '5_4_16',
				difficulty: Difficulty.EXPERT,
				groupId: '16',
				grid: [
					[E, E, E, E, E],
					[E, E, E, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '6_4_16',
				difficulty: Difficulty.EXPERT,
				groupId: '16',
				grid: [
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '7_4_16',
				difficulty: Difficulty.EXPERT,
				groupId: '16',
				grid: [
					[F, F, F, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
				],
			},
		],
	},
	{
		groupId: '17',
		difficulty: Difficulty.EXPERT,
		obstacles: [
			{
				name: '1_4_17',
				difficulty: Difficulty.EXPERT,
				groupId: '17',
				grid: [
					[E, F, E, F, E],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[F, E, F, E, F],
					[E, F, F, F, E],
				],
			},
			{
				name: '2_4_17',
				difficulty: Difficulty.EXPERT,
				groupId: '17',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '3_4_17',
				difficulty: Difficulty.EXPERT,
				groupId: '17',
				grid: [
					[F, E, F, E, F],
					[F, ST, F, ST, F],
					[F, F, F, F, F],
					[E, F, F, F, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_4_17',
				difficulty: Difficulty.EXPERT,
				groupId: '17',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '5_4_17',
				difficulty: Difficulty.EXPERT,
				groupId: '17',
				grid: [
					[E, F, E, F, E],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[F, E, F, E, F],
					[E, F, F, F, E],
				],
			},
		],
	},
	{
		groupId: '18',
		difficulty: Difficulty.HARD,
		obstacles: [
			{
				name: '1_3_18',
				difficulty: Difficulty.HARD,
				groupId: '18',
				grid: [
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_3_18',
				difficulty: Difficulty.HARD,
				groupId: '18',
				grid: [
					[E, E, F, F, F],
					[E, E, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_3_18',
				difficulty: Difficulty.HARD,
				groupId: '18',
				grid: [
					[F, F, F, E, E],
					[F, F, F, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '19',
		difficulty: Difficulty.EASY,
		obstacles: [
			{
				name: '1_1_19',
				difficulty: Difficulty.EASY,
				groupId: '19',
				grid: [
					[E, F, E, E, E],
					[E, F, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '2_1_19',
				difficulty: Difficulty.EASY,
				groupId: '19',
				grid: [
					[E, E, E, E, E],
					[E, E, E, F, E],
					[E, E, E, F, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '3_1_19',
				difficulty: Difficulty.EASY,
				groupId: '19',
				grid: [
					[F, E, E, E, E],
					[F, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_1_19',
				difficulty: Difficulty.EASY,
				groupId: '19',
				grid: [
					[E, E, F, E, E],
					[E, E, F, E, E],
					[F, F, F, F, F],
					[E, E, F, E, E],
					[E, E, F, E, E],
				],
			},
			{
				name: '5_1_19',
				difficulty: Difficulty.EASY,
				groupId: '19',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
		],
	},
	{
		groupId: '2',
		difficulty: Difficulty.MASTER,
		obstacles: [
			{
				name: '10_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[E, E, F, F, F],
					[ST, ST, F, E, E],
					[F, F, F, E, E],
					[F, F, F, ST, ST],
					[F, F, F, F, F],
				],
			},
			{
				name: '1_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
				],
			},
			{
				name: '2_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '3_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[F, F, E, E, F],
					[F, F, E, E, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '5_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[F, F, F, E, E],
					[F, F, F, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '6_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '7_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[F, F, F, E, E],
					[F, F, F, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '8_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[E, E, F, F, F],
					[E, E, F, F, F],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '9_5_2',
				difficulty: Difficulty.MASTER,
				groupId: '2',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
		],
	},
	{
		groupId: '21',
		difficulty: Difficulty.NORMAL,
		obstacles: [
			{
				name: '1_2_21',
				difficulty: Difficulty.NORMAL,
				groupId: '21',
				grid: [
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_2_21',
				difficulty: Difficulty.NORMAL,
				groupId: '21',
				grid: [
					[E, E, F, E, E],
					[E, E, F, E, E],
					[E, E, F, E, E],
					[E, E, F, E, E],
					[E, E, F, E, E],
				],
			},
			{
				name: '3_2_21',
				difficulty: Difficulty.NORMAL,
				groupId: '21',
				grid: [
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
				],
			},
			{
				name: '4_2_21',
				difficulty: Difficulty.NORMAL,
				groupId: '21',
				grid: [
					[E, F, F, F, E],
					[ST, F, SB, F, ST],
					[F, F, E, F, F],
					[F, F, E, F, F],
					[E, F, F, F, E],
				],
			},
			{
				name: '5_2_21',
				difficulty: Difficulty.NORMAL,
				groupId: '21',
				grid: [
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '6_2_21',
				difficulty: Difficulty.NORMAL,
				groupId: '21',
				grid: [
					[E, E, E, E, E],
					[E, E, E, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '22',
		difficulty: Difficulty.MASTER,
		obstacles: [
			{
				name: '1_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, E, E],
				],
			},
			{
				name: '2_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, E, E],
				],
			},
			{
				name: '3_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[E, E, F, F, F],
					[E, E, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '4_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
				],
			},
			{
				name: '5_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
				],
			},
			{
				name: '6_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '7_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[E, E, F, F, F],
					[E, E, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '8_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[E, F, E, E, E],
					[E, F, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '9_5_22',
				difficulty: Difficulty.MASTER,
				groupId: '22',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
		],
	},
	{
		groupId: '23',
		difficulty: Difficulty.HARD,
		obstacles: [
			{
				name: '1_3_23',
				difficulty: Difficulty.HARD,
				groupId: '23',
				grid: [
					[F, F, F, F, F],
					[E, E, F, E, E],
					[E, E, F, E, E],
					[E, E, F, E, E],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_3_23',
				difficulty: Difficulty.HARD,
				groupId: '23',
				grid: [
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
				],
			},
			{
				name: '3_3_23',
				difficulty: Difficulty.HARD,
				groupId: '23',
				grid: [
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '4_3_23',
				difficulty: Difficulty.HARD,
				groupId: '23',
				grid: [
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '5_3_23',
				difficulty: Difficulty.HARD,
				groupId: '23',
				grid: [
					[F, F, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
				],
			},
			{
				name: '6_3_23',
				difficulty: Difficulty.HARD,
				groupId: '23',
				grid: [
					[E, E, E, E, E],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '24',
		difficulty: Difficulty.EASY,
		obstacles: [
			{
				name: '1_1_24',
				difficulty: Difficulty.EASY,
				groupId: '24',
				grid: [
					[E, E, F, E, E],
					[E, E, F, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[E, E, E, E, E],
				],
			},
			{
				name: '2_1_24',
				difficulty: Difficulty.EASY,
				groupId: '24',
				grid: [
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_1_24',
				difficulty: Difficulty.EASY,
				groupId: '24',
				grid: [
					[F, F, E, E, F],
					[F, F, E, E, F],
					[F, F, E, E, F],
					[F, F, E, E, F],
					[F, F, E, E, F],
				],
			},
			{
				name: '4_1_24',
				difficulty: Difficulty.EASY,
				groupId: '24',
				grid: [
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
				],
			},
			{
				name: '5_1_24',
				difficulty: Difficulty.EASY,
				groupId: '24',
				grid: [
					[E, E, E, E, E],
					[E, F, E, E, E],
					[E, F, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
		],
	},
	{
		groupId: '25',
		difficulty: Difficulty.HARD,
		obstacles: [
			{
				name: '1_3_25',
				difficulty: Difficulty.HARD,
				groupId: '25',
				grid: [
					[E, E, E, E, E],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '2_3_25',
				difficulty: Difficulty.HARD,
				groupId: '25',
				grid: [
					[E, E, E, E, E],
					[F, ST, F, ST, F],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '3_3_25',
				difficulty: Difficulty.HARD,
				groupId: '25',
				grid: [
					[E, E, E, E, E],
					[ST, F, ST, F, ST],
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_3_25',
				difficulty: Difficulty.HARD,
				groupId: '25',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '3',
		difficulty: Difficulty.EASY,
		obstacles: [
			{
				name: '1_1_3',
				difficulty: Difficulty.EASY,
				groupId: '3',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '2_1_3',
				difficulty: Difficulty.EASY,
				groupId: '3',
				grid: [
					[E, E, F, E, E],
					[E, E, F, E, E],
					[F, F, F, F, F],
					[E, E, F, E, E],
					[E, E, F, E, E],
				],
			},
			{
				name: '3_1_3',
				difficulty: Difficulty.EASY,
				groupId: '3',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_1_3',
				difficulty: Difficulty.EASY,
				groupId: '3',
				grid: [
					[E, E, F, E, E],
					[E, E, F, E, E],
					[F, F, F, F, F],
					[E, E, F, E, E],
					[E, E, F, E, E],
				],
			},
			{
				name: '5_1_3',
				difficulty: Difficulty.EASY,
				groupId: '3',
				grid: [
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '6',
		difficulty: Difficulty.EXPERT,
		obstacles: [
			{
				name: '1_4_6',
				difficulty: Difficulty.EXPERT,
				groupId: '6',
				grid: [
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
				],
			},
			{
				name: '2_4_6',
				difficulty: Difficulty.EXPERT,
				groupId: '6',
				grid: [
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
					[E, F, F, F, E],
				],
			},
			{
				name: '3_4_6',
				difficulty: Difficulty.EXPERT,
				groupId: '6',
				grid: [
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
				],
			},
			{
				name: '4_4_6',
				difficulty: Difficulty.EXPERT,
				groupId: '6',
				grid: [
					[F, E, E, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
				],
			},
			{
				name: '5_4_6',
				difficulty: Difficulty.EXPERT,
				groupId: '6',
				grid: [
					[F, F, E, E, F],
					[F, F, E, E, F],
					[F, F, E, E, F],
					[F, F, E, E, F],
					[F, F, E, E, F],
				],
			},
			{
				name: '6_4_6',
				difficulty: Difficulty.EXPERT,
				groupId: '6',
				grid: [
					[F, E, E, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
					[F, E, E, F, F],
				],
			},
			{
				name: '7_4_6',
				difficulty: Difficulty.EXPERT,
				groupId: '6',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '8_4_6',
				difficulty: Difficulty.EXPERT,
				groupId: '6',
				grid: [
					[E, E, E, E, E],
					[ST, ST, ST, ST, ST],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
		],
	},
	{
		groupId: '7',
		difficulty: Difficulty.EASY,
		obstacles: [
			{
				name: '1_1_7',
				difficulty: Difficulty.EASY,
				groupId: '7',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '2_1_7',
				difficulty: Difficulty.EASY,
				groupId: '7',
				grid: [
					[E, E, E, E, E],
					[E, E, E, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_1_7',
				difficulty: Difficulty.EASY,
				groupId: '7',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_1_7',
				difficulty: Difficulty.EASY,
				groupId: '7',
				grid: [
					[E, E, E, E, E],
					[E, E, E, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '5_1_7',
				difficulty: Difficulty.EASY,
				groupId: '7',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '8_1_7',
				difficulty: Difficulty.EASY,
				groupId: '7',
				grid: [
					[E, E, E, E, E],
					[E, E, E, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '9_1_7',
				difficulty: Difficulty.EASY,
				groupId: '7',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
		],
	},
	{
		groupId: '8',
		difficulty: Difficulty.NORMAL,
		obstacles: [
			{
				name: '1_2_8',
				difficulty: Difficulty.NORMAL,
				groupId: '8',
				grid: [
					[F, F, F, F, F],
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, ST, ST],
					[F, F, F, F, F],
				],
			},
			{
				name: '2_2_8',
				difficulty: Difficulty.NORMAL,
				groupId: '8',
				grid: [
					[F, F, F, E, E],
					[F, F, F, E, E],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '3_2_8',
				difficulty: Difficulty.NORMAL,
				groupId: '8',
				grid: [
					[F, F, F, F, F],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
					[E, E, E, E, E],
				],
			},
			{
				name: '4_2_8',
				difficulty: Difficulty.NORMAL,
				groupId: '8',
				grid: [
					[E, E, F, F, F],
					[E, E, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '5_2_8',
				difficulty: Difficulty.NORMAL,
				groupId: '8',
				grid: [
					[F, F, F, F, F],
					[E, E, F, F, F],
					[E, E, F, F, F],
					[ST, ST, F, F, F],
					[F, F, F, F, F],
				],
			},
			{
				name: '6_2_8',
				difficulty: Difficulty.NORMAL,
				groupId: '8',
				grid: [
					[F, E, E, E, F],
					[F, E, E, E, F],
					[F, F, F, F, F],
					[F, E, E, E, F],
					[F, E, E, E, F],
				],
			},
		],
	},
]
